function batch = batch_erp_load_params_aurora(task, phase, batch_tag, computer,run_tag)
%% BATCH_ERP_LOAD_PARAMS: loads preset processing information into struct
% Inputs:
%   - task     -  char | SPA task to calculate ERPs for
%                 'tth', 'tss', 'sl', 'ath', 'tss_a', 'rl1', or 'rl2'
%   - phase    -  char | phase of SPA data to use | 'study' or 'pilot'
%   - batch_tag - char | '' or tag to append to batch filename
%   - computer -  char | 'pc' or 'mac', for filepaths
% Outputs:
%   - batch - struct containing batch parameters such as:
%       - roi_1020    - cells containing ROIs defined by 10-20 chans 
%       - roi_other   - arrays containing ROIs defined by chan numbers
%       - roi_weight - arrays containing weights to apply to each ROI
%       - peak_time   - arrays of times in ms with ERP peaks (per ROI)
%       - peak_win_size   - arrays of temporal window width in ms for ERP
%       - peak_name  - name to label ERP plots with (per time plotted)
% Author: Gerardo Parra, 2022-07-28

%% set data locations
% path on server to general data folder
data_path = fullfile('Groups','SPA','01_Data_Raw_Summary_Processed');
switch computer
    case 'mac', data_path = fullfile('Volumes','neuro-levin',data_path);
    case 'pc',  data_path = fullfile('Z:',data_path);
end
% path to folder with EEG data
switch phase
    case 'study'
        eeg_path = fullfile( data_path, 'EEG', 'Participant_Data',      ...
                             '03_Processed_Data' );
    case 'pilot_raw'
        eeg_path = fullfile( data_path, 'EEG', 'Pilot_Data',      ...
                             '03_Processed_Data' );
    otherwise
        error(['Information not set up for ' phase ' data'])
end
batch.avg_rise_decay = 0;
switch task
    case 'Aurora'
        task_folder = '09_Aurora'
        %% Tactile Spatial Suppression
        % analysis specifications inspired by:
        % - Espenhahn et al 2021: P50 (30–55  ms), N80 (55–80 ms), and P100
        %   (80–125 ms), N140 (150–210  ms), P300 (270–300  ms), N190
        %   (150-240 ms), N300 (280-400 ms)
        % chosen windows:
        % - P100 (50-125 ms), N140 (150-210 ms), P300 (225-300 ms), 
        %   P4 (300-425 ms), P190 (140-240 ms), N300 (280-425 ms)
        batch.beapp_tag = '_updated_trials_updated_trigger_notch_erpfilt_blcorr';
        batch.reseg_tag = '_500ms_wins__ERP_filters_notch_no_linenoise_54_taps_nobc';
        %batch.beapp_tag = '_ERP_filters_notch_no_linenoise_54_taps_nobc';
        batch.beapp_tag = '_3_14_23_notch_filt_50msbl';
                batch.beapp_tag = '_3_16_23_notch_filt_100msbl_jointprob_trialalign';
             %   batch.beapp_tag = '_3_16_23_bl';
%batch.beapp_tag = '_3_16_23_notch_filt_100msbl_jointprob_lindet';
        batch.roi_1020  = {                                     ...
                             {'C3','C4'},                       ...
                             {'C3'},                            ...
                             {},                                ...
                             {'Fz'}                             ...
                             {}                             ...
                           };
        batch.roi_other    = {                                      ...
                                 [],                                ...
                                 [],                                ...
                                 [30 36 41],                           ...
                                 []    ,                             ...
                                 [75],                               ...
                               };
        batch.roi_weight   = {                                      ...
                                 [1 -1],                            ...
                                 [],                                ...
                                 [],                                ...
                                 []                                 ...
                                 []                                 ...
                               };
      %  batch.peak_time     = {                                     ...
%                                  [13 25 45.0 80 87.5 140.0 262.5 362.5],    ...
%                                  [13 25 45.0 80 87.5 140.0 262.5 362.5],    ...
%                                  [13 25 45.0 80 87.5 140.0 262.5 362.5],    ...
%                                  [190.0 352.5]                      ...
%                                  [13 25 45.0 80 87.5 140.0 262.5 362.5],    ...

  batch.peak_time     = {                                     ...
                                 [13 20 25 42.5 77.5 102.5 140.0 262.5 362.5],    ...
                                 [13 20 25 45.0 80 87.5 140.0 262.5 362.5],    ...
                                 [13 20 25 45.0 80 87.5 140.0 262.5 362.5],    ...
                                 [190.0 352.5]                      ...
                                 [13 20 25 45.0 80 87.5 140.0 262.5 362.5],    ...
%P50 (30–55  ms), 
%N80 (55–80 ms), and P100 (80–125 ms) N140 (150-210)
                               };
        batch.peak_win_size  = {                                    ...
                                 [3 2 3 12.5 22.5 22.5  30.0  37.5  62.5],    ...
                                 [3 2 3 10.0 20 45  30.0  37.5  62.5],    ...
                                 [3 2 3 10.0 20 45  30.0  37.5  62.5],    ...
                                 [ 50.0  72.5]                      ...
                                  [3 2 3 10.0 20 37.5  30.0  37.5  62.5],    ...
                               };
        batch.peak_name = {                                             ...
                             {'N13','N20','P25','P50','N80','P100','N140','P300','P4'},         ...
                             {'N13','N20','P25','P50','N80','P100','N140','P300','P4'},         ...
                             {'N13','N20','P25','P50','N80','P100','N140','P300','P4'},         ...
                             {'P190','N300'}                            ...
                             {'N13','N20','P25','P50','N80','P100','N140','P300','P4'},         ...

                          };
        batch.peak_polarity = {                                         ...
                                 [0 0 1 1 0 1 0 1 1],                           ...
                                 [0 0 1 1 0 1 0 1 1],                           ...
                                 [0 0 1 1 0 1 0 1 1],                           ...
                                 [1 0]                                  ...
                                 [0 0 1 1 0 1 0 1 1],                           ...
                               };

        case 'Aurora_Adult'
            task_folder = '01_Aurora_Adult_Pilot\02_Aurora_mffs';
        %% Tactile Spatial Suppression
        % analysis specifications inspired by:
        % - Espenhahn et al 2021: P50 (30–55  ms), N80 (55–80 ms), and P100
        %   (80–125 ms), N140 (150–210  ms), P300 (270–300  ms), N190
        %   (150-240 ms), N300 (280-400 ms)
        % chosen windows:
        % - P100 (50-125 ms), N140 (150-210 ms), P300 (225-300 ms), 
        %   P4 (300-425 ms), P190 (140-240 ms), N300 (280-425 ms)
        
                batch.beapp_tag = '_3_16_23_notch_filt_100msbl_30_200_aligned';
             %   batch.beapp_tag = '_3_16_23_bl';
%batch.beapp_tag = '_3_16_23_notch_filt_100msbl_jointprob_lindet';
batch.beapp_tag = '_aligned';
        batch.roi_1020  = {                                     ...
                             {'C3','C4'},                       ...
                             {'C3'},                            ...
                             {},                                ...
                             {}, ...
                             {},...
                             {},...
                             {'Fz'}                             ...
                             {}                             ...
                           };
        batch.roi_other    = {                                      ...
                                 [],                                ...
                                 [],                                ...
                                 [30 36 41 ], ...
                                 [37 ], ...
                                 [42 ], ...
                                 [52],                           ... %37 42 cp1 cp2
                                 []    ,                             ...
                                 [75],                               ...
                               };
        batch.roi_weight   = {                                      ...
                                 [1 -1],                            ...
                                 [],                                ...
                                  [],                                ...
                                 [],                                ...
                                 [],                                ...
                                 [],                                ...
                                 []                                 ...
                                 []                                 ...
                               };
        batch.peak_time     = {                                     ...
                                 [13 20 25 42.5 77.5 102.5 140.0 262.5 362.5],    ...
                                 [13 20 25 45.0 80 87.5 140.0 262.5 362.5],    ...
                                 [13 20 25 45.0 80 87.5 140.0 262.5 362.5],    ...
                                 [13 20 25 45.0 80 87.5 140.0 262.5 362.5],  ...
                                 [13 20 25 45.0 80 87.5 140.0 262.5 362.5],    ...
                                 [13 20 25 45.0 80 87.5 140.0 262.5 362.5],    ...
                                 [190.0 352.5]                      ...
                                 [13 20 25 45.0 80 87.5 140.0 262.5 362.5],    ...
%P50 (30–55  ms), 
%N80 (55–80 ms), and P100 (80–125 ms) N140 (150-210)
                               };
        batch.peak_win_size  = {                                    ...
                                 [3 2 3 12.5 22.5 22.5  30.0  37.5  62.5],    ...
                                 [3 2 3 10.0 20 45  30.0  37.5  62.5],    ...
                                 [3 2 3 10.0 20 45  30.0  37.5  62.5],    ...
                                 [3 2 3 10.0 20 45  30.0  37.5  62.5],    ...
                                 [3 2 3 10.0 20 45  30.0  37.5  62.5],    ...
                                 [3 2 3 10.0 20 45  30.0  37.5  62.5],    ...
                                 [ 50.0  72.5]                      ...
                                  [3 2 3 10.0 20 37.5  30.0  37.5  62.5],    ...
                               };
        batch.peak_name = {                                             ...
                             {'N13','N20','P25','P50','N80','P100','N140','P300','P4'},         ...
                             {'N13','N20','P25','P50','N80','P100','N140','P300','P4'},         ...
                             {'N13','N20','P25','P50','N80','P100','N140','P300','P4'},         ...
                             {'N13','N20','P25','P50','N80','P100','N140','P300','P4'},         ...
                             {'N13','N20','P25','P50','N80','P100','N140','P300','P4'},         ...
                             {'N13','N20','P25','P50','N80','P100','N140','P300','P4'},         ...
                             {'P190','N300'}                            ...
                             {'N13','N20','P25','P50','N80','P100','N140','P300','P4'},         ...

                          };
        batch.peak_polarity = {                                         ...
                                 [0 0 1 1 0 1 0 1 1],                           ...
                                 [0 0 1 1 0 1 0 1 1],                           ...
                                 [0 0 1 1 0 1 0 1 1],                           ...
                                 [0 0 1 1 0 1 0 1 1],                           ...
                                 [0 0 1 1 0 1 0 1 1],                           ...
                                 [0 0 1 1 0 1 0 1 1],                           ...
                                 [1 0]                                  ...
                                 [0 0 1 1 0 1 0 1 1],                           ...
                               };


end

%% get and save subject group information
% get group assignments table
% grps_path  = fullfile(eeg_path,'01_Subject_Info_For_Processing');
% grps_fname = fullfile(grps_path,'Group_Assignments.mat');
% load(grps_fname,'groups')
% batch.groups.table = groups;
% 
% % get ids for each group
% group_names = {'TD','ASD','SPD'};
% for i_g = 1:3
%     group    = group_names{i_g};
%     grp_idxs = groups.group == i_g;
%     batch.groups.(group).table_idxs  = grp_idxs;
%     batch.groups.(group).subject_ids = groups.id(grp_idxs);
% end

%% get and save relevant filepaths
% save data filepaths 
task_path = fullfile(eeg_path,task_folder);
task_path =      'C:\Users\ch220650\Documents\02_Programming_Projects\03_BCH_Projects\Aurora_files\segment_aligned';

batch.task = task;
batch.tatask = task_path;
batch.path_task_eeg  = fullfile(task_path,['segment_' run_tag]);
batch.path_task_erp  = fullfile(task_path,'erp');
batch.path_task_figs = fullfile(task_path,'figures','erp');

% load beapp group_proc_info, save path, and get batch segmentation window
gpi_folder = fullfile(task_path,['out' batch.beapp_tag]);
gpi_fname  = ['Run_Report_Variables_and_settings' batch.beapp_tag '.mat'];
gpi_path   = fullfile(gpi_folder,gpi_fname);
load(gpi_path,'grp_proc_info'); gpi = grp_proc_info; clear grp_proc_info;
batch.seg_win = [ gpi.evt_seg_win_start gpi.evt_seg_win_end ] * 1000;
batch.path_task_gpi = gpi_path;
batch.srate = gpi.beapp_rsamp_srate;

% get batch time
t = get_date_str();
batch.batch_time = t;

% get batch filename
switch phase
    case 'study'
        % get filename to save batch to
        batch.batch_fname   = ['erp' batch.beapp_tag '_' t '_' batch_tag];
        if strcmp(task,'sl')
            if batch.avg_rise_decay
                batch.batch_fname = [batch.batch_fname '_rise-decay_avg'];
            end
        end
        batch.batch_fname = [batch.batch_fname '.mat'];
        
    case 'pilot_raw'
        % get filename to save batch to
        batch.batch_fname = ['erp' batch.beapp_tag '_' t '_' batch_tag];
        batch.batch_fname = [batch.batch_fname '.mat'];

    otherwise
        error(['Information not set up for ' phase ' data'])
end

end